/// @author Vojtěch Novotný - xnovot1f
/// @changes 50%
/// Some GPIO interrupt handling macros.
/// Made by hand, not entirely generated.
/// @date 23.12.2019

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/* Alias for GPIOC peripheral */
#define GPIO_BUTTON_GPIO GPIOE
/* Alias for PORTC */
#define GPIO_BUTTON_PORT PORTE
/* GPIO_BUTTON interrupt vector ID (number). */
#define GPIO_BUTTON_IRQN PORTE_IRQn
/* GPIO_BUTTON interrupt handler identifier. */
#define IRQ_SWITCHES PORTE_IRQHandler

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
