/// @author Vojtěch Novotný - xnovot1f
/// @changes 70%
/// Setup and initialization for GPIO ports. Macros and functions for GPIO manipulation.
/// @date 23.12.2019

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MK60DN512xxx10
package_id: MK60DN512VMD10
mcu_data: ksdk2_0
processor_version: 6.0.0
pin_labels:
- {pin_num: G12, pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, label: D12, identifier: xd;D9;D12}
- {pin_num: G11, pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, label: D11, identifier: D11}
- {pin_num: G10, pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/FTM1_FLT0, label: D10, identifier: D10}
- {pin_num: G9, pin_signal: ADC1_SE11/PTB5/ENET0_1588_TMR3/FTM2_FLT0, label: D9, identifier: D9}
- {pin_num: F1, pin_signal: PTE10/UART5_CTS_b/I2S0_TXD0, label: SW2, identifier: SW2}
- {pin_num: G4, pin_signal: PTE11/UART5_RTS_b/I2S0_TX_FS, label: SW6, identifier: SW;WS6;SW6}
- {pin_num: G3, pin_signal: PTE12/I2S0_TX_BCLK, label: SW3, identifier: SW3}
- {pin_num: K4, pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, label: SW5, identifier: SW5}
- {pin_num: J4, pin_signal: PTE27/UART4_RTS_b, label: SW4, identifier: SW4}
- {pin_num: L7, pin_signal: TSI0_CH5/PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, label: Speaker, identifier: Speaker}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: G12, peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, identifier: D12, direction: OUTPUT}
  - {pin_num: G11, peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, direction: OUTPUT}
  - {pin_num: G10, peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/FTM1_FLT0, direction: OUTPUT}
  - {pin_num: G9, peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: ADC1_SE11/PTB5/ENET0_1588_TMR3/FTM2_FLT0, direction: OUTPUT}
  - {pin_num: F1, peripheral: GPIOE, signal: 'GPIO, 10', pin_signal: PTE10/UART5_CTS_b/I2S0_TXD0, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge, pull_select: up,
    pull_enable: enable}
  - {pin_num: G4, peripheral: GPIOE, signal: 'GPIO, 11', pin_signal: PTE11/UART5_RTS_b/I2S0_TX_FS, identifier: SW6, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge,
    pull_select: up, pull_enable: enable}
  - {pin_num: G3, peripheral: GPIOE, signal: 'GPIO, 12', pin_signal: PTE12/I2S0_TX_BCLK, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge, pull_select: up,
    pull_enable: enable}
  - {pin_num: K4, peripheral: GPIOE, signal: 'GPIO, 26', pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge,
    pull_select: up, pull_enable: enable}
  - {pin_num: J4, peripheral: GPIOE, signal: 'GPIO, 27', pin_signal: PTE27/UART4_RTS_b, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge, pull_select: up,
    pull_enable: enable}
  - {pin_num: L7, peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: TSI0_CH5/PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t Speaker_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin L7)  */
    GPIO_PinInit(BOARD_INITPINS_Speaker_GPIO, BOARD_INITPINS_Speaker_PIN, &Speaker_config);

    gpio_pin_config_t D12_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin G12)  */
    GPIO_PinInit(BOARD_INITPINS_D12_GPIO, BOARD_INITPINS_D12_PIN, &D12_config);

    gpio_pin_config_t D11_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin G11)  */
    GPIO_PinInit(BOARD_INITPINS_D11_GPIO, BOARD_INITPINS_D11_PIN, &D11_config);

    gpio_pin_config_t D10_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin G10)  */
    GPIO_PinInit(BOARD_INITPINS_D10_GPIO, BOARD_INITPINS_D10_PIN, &D10_config);

    gpio_pin_config_t D9_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin G9)  */
    GPIO_PinInit(BOARD_INITPINS_D9_GPIO, BOARD_INITPINS_D9_PIN, &D9_config);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE10 (pin F1)  */
    GPIO_PinInit(BOARD_INITPINS_SW2_GPIO, BOARD_INITPINS_SW2_PIN, &SW2_config);

    gpio_pin_config_t SW6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE11 (pin G4)  */
    GPIO_PinInit(BOARD_INITPINS_SW6_GPIO, BOARD_INITPINS_SW6_PIN, &SW6_config);

    gpio_pin_config_t SW3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE12 (pin G3)  */
    GPIO_PinInit(BOARD_INITPINS_SW3_GPIO, BOARD_INITPINS_SW3_PIN, &SW3_config);

    gpio_pin_config_t SW5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE26 (pin K4)  */
    GPIO_PinInit(BOARD_INITPINS_SW5_GPIO, BOARD_INITPINS_SW5_PIN, &SW5_config);

    gpio_pin_config_t SW4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE27 (pin J4)  */
    GPIO_PinInit(BOARD_INITPINS_SW4_GPIO, BOARD_INITPINS_SW4_PIN, &SW4_config);

    /* PORTA4 (pin L7) is configured as PTA4 */
    PORT_SetPinMux(BOARD_INITPINS_Speaker_PORT, BOARD_INITPINS_Speaker_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin G12) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_D12_PORT, BOARD_INITPINS_D12_PIN, kPORT_MuxAsGpio);

    /* PORTB3 (pin G11) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_D11_PORT, BOARD_INITPINS_D11_PIN, kPORT_MuxAsGpio);

    /* PORTB4 (pin G10) is configured as PTB4 */
    PORT_SetPinMux(BOARD_INITPINS_D10_PORT, BOARD_INITPINS_D10_PIN, kPORT_MuxAsGpio);

    /* PORTB5 (pin G9) is configured as PTB5 */
    PORT_SetPinMux(BOARD_INITPINS_D9_PORT, BOARD_INITPINS_D9_PIN, kPORT_MuxAsGpio);

    /* PORTE10 (pin F1) is configured as PTE10 */
    PORT_SetPinMux(BOARD_INITPINS_SW2_PORT, BOARD_INITPINS_SW2_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE10 (pin F1): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW2_PORT, BOARD_INITPINS_SW2_PIN, kPORT_InterruptFallingEdge);

    PORTE->PCR[10] = ((PORTE->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding Port Pull Enable Register field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTE11 (pin G4) is configured as PTE11 */
    PORT_SetPinMux(BOARD_INITPINS_SW6_PORT, BOARD_INITPINS_SW6_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE11 (pin G4): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW6_PORT, BOARD_INITPINS_SW6_PIN, kPORT_InterruptFallingEdge);

    PORTE->PCR[11] = ((PORTE->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding Port Pull Enable Register field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTE12 (pin G3) is configured as PTE12 */
    PORT_SetPinMux(BOARD_INITPINS_SW3_PORT, BOARD_INITPINS_SW3_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE12 (pin G3): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW3_PORT, BOARD_INITPINS_SW3_PIN, kPORT_InterruptFallingEdge);

    PORTE->PCR[12] = ((PORTE->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding Port Pull Enable Register field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTE26 (pin K4) is configured as PTE26 */
    PORT_SetPinMux(BOARD_INITPINS_SW5_PORT, BOARD_INITPINS_SW5_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE26 (pin K4): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW5_PORT, BOARD_INITPINS_SW5_PIN, kPORT_InterruptFallingEdge);

    PORTE->PCR[26] = ((PORTE->PCR[26] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding Port Pull Enable Register field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTE27 (pin J4) is configured as PTE27 */
    PORT_SetPinMux(BOARD_INITPINS_SW4_PORT, BOARD_INITPINS_SW4_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE27 (pin J4): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW4_PORT, BOARD_INITPINS_SW4_PIN, kPORT_InterruptFallingEdge);

    PORTE->PCR[27] = ((PORTE->PCR[27] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding Port Pull Enable Register field is set. */
                      | (uint32_t)(kPORT_PullUp));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
